# Generated by Django 5.1.4 on 2026-05-28 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('abbr', models.CharField(max_length=3)),
                ('has_professional_tax', models.BooleanField(default=False)),
                ('prof_tax_slabs_json', models.TextField(blank=True)),
                ('gst_state_code', models.CharField(blank=True, max_length=2)),
                ('special_notes', models.TextField(blank=True)),
                ('meta_title', models.CharField(max_length=70)),
                ('meta_description', models.CharField(max_length=165)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
