# Generated by Django 5.1.4 on 2026-05-30 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='market',
            field=models.CharField(choices=[('india', 'India'), ('us', 'United States'), ('global', 'Global')], default='india', max_length=10),
        ),
    ]
