# Generated by Django 5.0.14 on 2026-06-08 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_add_ai_generation_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeywordResearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed_keyword', models.CharField(max_length=300)),
                ('keyword', models.CharField(max_length=300, unique=True)),
                ('intent', models.CharField(blank=True, choices=[('Informational', 'Informational'), ('Transactional', 'Transactional'), ('Commercial', 'Commercial'), ('Navigational', 'Navigational')], max_length=30)),
                ('search_volume', models.CharField(blank=True, max_length=30)),
                ('kd', models.IntegerField(default=0, help_text='Keyword Difficulty 0-100')),
                ('cpc', models.CharField(blank=True, max_length=20)),
                ('priority', models.CharField(blank=True, choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=10)),
                ('market', models.CharField(default='india', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='keywords', to='blog.article')),
            ],
            options={
                'verbose_name': 'Keyword',
                'verbose_name_plural': 'Keyword Research',
                'ordering': ['kd'],
            },
        ),
    ]
