# Generated by Django 5.0.14 on 2026-06-08 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_add_keyword_research'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword_model', models.CharField(choices=[('anthropic/claude-sonnet-4.6', 'Claude Sonnet 4.6  — $3.00/1M  ★ Best quality'), ('anthropic/claude-sonnet-4.5', 'Claude Sonnet 4.5  — $3.00/1M'), ('anthropic/claude-haiku-4.5', 'Claude Haiku 4.5   — $1.00/1M  ⚡ Fast'), ('anthropic/claude-opus-4.8', 'Claude Opus 4.8    — $5.00/1M  🏆 Top tier'), ('google/gemini-2.5-pro', 'Gemini 2.5 Pro     — $1.25/1M  🔬 Deep research'), ('google/gemini-2.5-flash', 'Gemini 2.5 Flash   — $0.30/1M  ⚡ Balanced'), ('google/gemini-2.5-flash-lite', 'Gemini 2.5 Flash Lite — $0.10/1M 💰 Ultra cheap'), ('google/gemini-3.1-flash-lite', 'Gemini 3.1 Flash Lite — $0.25/1M'), ('google/gemini-3.5-flash', 'Gemini 3.5 Flash   — $1.50/1M  🆕 Latest'), ('deepseek/deepseek-chat-v3-0324', 'DeepSeek V3        — $0.20/1M  💰 Cheap bulk'), ('deepseek/deepseek-v3.1-terminus', 'DeepSeek V3.1      — $0.27/1M'), ('deepseek/deepseek-v4-flash', 'DeepSeek V4 Flash  — $0.10/1M  💰 Cheapest'), ('deepseek/deepseek-r1-0528', 'DeepSeek R1        — $0.50/1M  🧠 Reasoning'), ('openai/gpt-4o', 'GPT-4o             — $2.50/1M'), ('openai/gpt-4o-mini', 'GPT-4o Mini        — $0.15/1M  💰 Cheap')], default='google/gemini-2.5-pro', help_text='Used by: python manage.py keyword_research', max_length=100, verbose_name='Keyword Research Model')),
                ('article_model', models.CharField(choices=[('anthropic/claude-sonnet-4.6', 'Claude Sonnet 4.6  — $3.00/1M  ★ Best quality'), ('anthropic/claude-sonnet-4.5', 'Claude Sonnet 4.5  — $3.00/1M'), ('anthropic/claude-haiku-4.5', 'Claude Haiku 4.5   — $1.00/1M  ⚡ Fast'), ('anthropic/claude-opus-4.8', 'Claude Opus 4.8    — $5.00/1M  🏆 Top tier'), ('google/gemini-2.5-pro', 'Gemini 2.5 Pro     — $1.25/1M  🔬 Deep research'), ('google/gemini-2.5-flash', 'Gemini 2.5 Flash   — $0.30/1M  ⚡ Balanced'), ('google/gemini-2.5-flash-lite', 'Gemini 2.5 Flash Lite — $0.10/1M 💰 Ultra cheap'), ('google/gemini-3.1-flash-lite', 'Gemini 3.1 Flash Lite — $0.25/1M'), ('google/gemini-3.5-flash', 'Gemini 3.5 Flash   — $1.50/1M  🆕 Latest'), ('deepseek/deepseek-chat-v3-0324', 'DeepSeek V3        — $0.20/1M  💰 Cheap bulk'), ('deepseek/deepseek-v3.1-terminus', 'DeepSeek V3.1      — $0.27/1M'), ('deepseek/deepseek-v4-flash', 'DeepSeek V4 Flash  — $0.10/1M  💰 Cheapest'), ('deepseek/deepseek-r1-0528', 'DeepSeek R1        — $0.50/1M  🧠 Reasoning'), ('openai/gpt-4o', 'GPT-4o             — $2.50/1M'), ('openai/gpt-4o-mini', 'GPT-4o Mini        — $0.15/1M  💰 Cheap')], default='anthropic/claude-sonnet-4.6', help_text='Used by: python manage.py generate_article (single article)', max_length=100, verbose_name='Article Generation Model')),
                ('bulk_model', models.CharField(choices=[('anthropic/claude-sonnet-4.6', 'Claude Sonnet 4.6  — $3.00/1M  ★ Best quality'), ('anthropic/claude-sonnet-4.5', 'Claude Sonnet 4.5  — $3.00/1M'), ('anthropic/claude-haiku-4.5', 'Claude Haiku 4.5   — $1.00/1M  ⚡ Fast'), ('anthropic/claude-opus-4.8', 'Claude Opus 4.8    — $5.00/1M  🏆 Top tier'), ('google/gemini-2.5-pro', 'Gemini 2.5 Pro     — $1.25/1M  🔬 Deep research'), ('google/gemini-2.5-flash', 'Gemini 2.5 Flash   — $0.30/1M  ⚡ Balanced'), ('google/gemini-2.5-flash-lite', 'Gemini 2.5 Flash Lite — $0.10/1M 💰 Ultra cheap'), ('google/gemini-3.1-flash-lite', 'Gemini 3.1 Flash Lite — $0.25/1M'), ('google/gemini-3.5-flash', 'Gemini 3.5 Flash   — $1.50/1M  🆕 Latest'), ('deepseek/deepseek-chat-v3-0324', 'DeepSeek V3        — $0.20/1M  💰 Cheap bulk'), ('deepseek/deepseek-v3.1-terminus', 'DeepSeek V3.1      — $0.27/1M'), ('deepseek/deepseek-v4-flash', 'DeepSeek V4 Flash  — $0.10/1M  💰 Cheapest'), ('deepseek/deepseek-r1-0528', 'DeepSeek R1        — $0.50/1M  🧠 Reasoning'), ('openai/gpt-4o', 'GPT-4o             — $2.50/1M'), ('openai/gpt-4o-mini', 'GPT-4o Mini        — $0.15/1M  💰 Cheap')], default='deepseek/deepseek-chat-v3-0324', help_text='Used by: admin "Generate articles" bulk action', max_length=100, verbose_name='Bulk Generation Model')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Model Configuration',
                'verbose_name_plural': 'AI Model Configuration',
            },
        ),
    ]
