# Generated by Django 5.1.4 on 2026-05-28 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('short_desc', models.CharField(max_length=300)),
                ('category', models.CharField(choices=[('regime', 'Regime Comparison'), ('income', 'Income Tax'), ('deductions', 'Deductions & Savings'), ('freelancer', 'Freelancer & Business'), ('gst', 'GST'), ('investment', 'Investments & Capital Gains'), ('retirement', 'Retirement & Savings'), ('utility', 'Utility Tools')], max_length=30)),
                ('icon', models.CharField(default='calculator', max_length=50)),
                ('is_featured', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('rating_up', models.IntegerField(default=0)),
                ('rating_down', models.IntegerField(default=0)),
                ('meta_title', models.CharField(max_length=70)),
                ('meta_description', models.CharField(max_length=165)),
                ('fy_applicable', models.CharField(default='2025-26', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
