# Generated by Django 5.1.4 on 2026-05-30 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='market',
            field=models.CharField(choices=[('india', 'India'), ('us', 'United States'), ('global', 'Global')], default='india', max_length=10),
        ),
        migrations.AlterField(
            model_name='tool',
            name='category',
            field=models.CharField(choices=[('regime', 'Regime Comparison'), ('income', 'Income Tax'), ('deductions', 'Deductions & Savings'), ('freelancer', 'Freelancer & Business'), ('gst', 'GST'), ('investment', 'Investments & Capital Gains'), ('retirement', 'Retirement & Savings'), ('utility', 'Utility Tools'), ('us_income', 'US Income Tax'), ('us_deductions', 'US Deductions'), ('us_self_employment', 'US Self-Employment'), ('us_investment', 'US Investments'), ('us_retirement', 'US Retirement')], max_length=30),
        ),
    ]
